Feature/devs
GagandeepKumar92/UsersDemo pull request #4
Opened 2022-04-20 07:17 UTC by GagandeepKumar92

Filter map changes

2022-04-20 11:06 UTC, sewak2610 requested changes

2022-04-20 11:06 UTC, sewak2610 commented on db/mongo/client.go
> +
remove this extra new line.

2022-04-20 12:20 UTC, GagandeepKumar92 commented on api/handlers/find_user.go
> +		log.Fatal(err)
Done. Kindly Check.

2022-04-20 12:21 UTC, GagandeepKumar92 commented on api/handlers/find_user.go
> +	us, err := f.rt.GetManager().ListUser(*fup.Limit, filteredMap(fup))
No, because in yml file default value of limit is 0.

2022-04-20 12:21 UTC, GagandeepKumar92 commented on db/client.go
>  	UpdateUser(*domain.User) error
Done. Kindly Check

2022-04-20 12:22 UTC, GagandeepKumar92 commented on db/mongo/client.go
> +
Done. Kindly Check

2022-04-21 10:23 UTC, sewak2610 commented
LGTM!!!
hope it is working as expected on your local.

2022-04-21 11:25 UTC, merged